#!/bin/bash
#this script transfer the relax cell and coordination to the POSCAR
#usage: ./qeout2in.sh outputfile inputfile $1 is the output result after relaxation
#and $2 is the input file relative the output file
#the script maily used to visiualize the qe output by VESTA
#ponychen  
#20190629
#email:18709821294@163.com

#get the relaxed atomic coordinations
atombegin=`grep -in "ATOMIC_POSITIONS" $1 | tail -1 | awk ' BEGIN{FS=":"} {print $1+1}'`
atomend=`grep -in "End final coor" $1 | awk ' BEGIN{FS=":"} {print $1-1}'`

atomnum=$(($atomend-$atombegin+1))
eval $( awk -v num=$atomnum -v begin=$atombegin -v end=$atomend '
    NR>=begin && NR<=end {x[NR-begin+1]=$2;y[NR-begin+1]=$3;z[NR-begin+1]=$4}
    END{for(i=1;i<=num;i++){
		printf("coor[%d]=\"%9.6f  %9.6f  %9.6f    \"\n",i,x[i],y[i],z[i])}}' $1)

#get the element symbol of all atom
eval $( awk -v num=$atomnum -v begin=$atombegin -v end=$atomend '
    NR>=begin && NR<=end {x[NR-begin+1]=$1;}
    END{for(i=1;i<=num;i++){
		printf("elements[%d]=\"%s\"\n", i,x[i])}}' $1)


#get the relaxed cell parameters if vc-relax are performed
cellbegin=`grep -in "CELL_PARAMETERS" $1 | tail -1 | awk 'BEGIN{FS=":"} {print $1+1}'`
cellend=$(($cellbegin+2))

if [ $cellbegin ];then
	eval $( awk -v begin=$cellbegin '
	NR>=begin && NR<=begin+2 {x[NR-begin+1]=$1;y[NR-begin+1]=$2;z[NR-begin+1]=$3}
END{for(i=1;i<=3;i++){
printf("cell[%d]=\"    %9.6f  %9.6f  %9.6f\"\n",i,x[i],y[i],z[i])}}' $1)
else
    cellbegin2=`grep -in "CELL_PARAMETERS" $2 | awk 'BEGIN{FS=":"} {print $1+1}'`
	cellend2=$(($cellbegin2+2))
	eval $( awk -v begin=$cellbegin2 '
	NR>=begin && NR<=begin+2 {x[NR-begin+1]=$1;y[NR-begin+1]=$2;z[NR-begin+1]=$3}
END{for(i=1;i<=3;i++){
printf("cell[%d]=\"    %9.6f  %9.6f  %9.6f\"\n",i,x[i],y[i],z[i])}}' $2)
fi

#get the element type and relative numbers in qe file
elebegin=`grep -in "ATOMIC_SPECIES" $2 | awk 'BEGIN{FS=":"} {print $1+1}'`
noempty="1"
itr=$elebegin
ini=0
until [ "$noempty" == "" ]
do
	eval $(awk -v itr=$itr -v ini=$ini '
	NR==itr {ns=$1}
END{printf("elespe[%d]=\"%s\"\n",ini,ns)}' $2)
noempty=${elespe[$ini]}
itr=$(($itr+1))
ini=$(($ini+1))
done
eletol=$(($ini-1))
for ((i=0;i<=$eletol;i++))
do
	for j in ${elements[*]}
	do
		if [ "$j" == "${elespe[$i]}" ];then
			elenum[$i]=$((${elenum[$i]}+1))
		fi
	done
done

#write to qe POSCAR
echo "generated by qeout2vasp.sh" > POSCAR
echo "	1.000000" >> POSCAR
for ((i=1;i<=3;i++))
do
	echo "${cell[$i]}" >> POSCAR
done

echo ${elespe[*]} >> POSCAR
echo ${elenum[*]} >> POSCAR

echo "Cartesian" >> POSCAR

for ((i=1;i<=$atomnum;i=i+1))
do
	echo "${coor[$i]}" >> POSCAR
done
